# Generated by Django 5.0.6 on 2024-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcupload', '0002_remove_buildingifc_id_alter_buildingifc_ref_bag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodDefenseMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_bag_id', models.CharField(max_length=255)),
                ('global_id', models.CharField(max_length=255)),
            ],
        ),
    ]
