# Generated by Django 5.0.6 on 2024-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcupload', '0003_flooddefensemechanism'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='class_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
