# Generated by Django 5.0.6 on 2025-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcupload', '0005_flooddefensemechanism_fragment_id_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
