# Generated by Django 5.0.6 on 2025-01-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcupload', '0006_flooddefensemechanism_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='category',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='flooddefensemechanism',
            name='year_of_review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flooddefensemechanism',
            name='fragment_id_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flooddefensemechanism',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flooddefensemechanism',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flooddefensemechanism',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
